server:
  port: 8082
  servlet:
    path: /cloud-feign

spring:
  application:
    name: cloud-feign
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/

feign:
  hystrix:
    enabled: true

sys:
  cintel:
    uploadUrl: http://127.0.0.1:8081